//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQNotificationService.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "12.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute("Data Source=(localdb)\\v11.0;Initial Catalog=solar_mobile_logging;Persist Security" +
            " Info=True;User ID=solarsqluser;Password=\"{your password here}\";Connect Timeout=" +
            "30;Encrypt=False")]
        public string LoggingConnectionString {
            get {
                return ((string)(this["LoggingConnectionString"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.ConnectionString)]
        [global::System.Configuration.DefaultSettingValueAttribute(@"metadata=res://*/Models.Database.NotificationServiceModel.csdl|res://*/Models.Database.NotificationServiceModel.ssdl|res://*/Models.Database.NotificationServiceModel.msl;provider=System.Data.SqlClient;provider connection string=&quot;data source=LTCMADUAKOLAM2\MSSQLSERVER1;initial catalog=solar_mobile_fdev;integrated security=True;multipleactiveresultsets=True;application name=EntityFramework&quot;""
      providerName=""System.Data.EntityClient"" ")]
        public string NotificationServiceDbContext {
            get {
                return ((string)(this["NotificationServiceDbContext"]));
            }
        }
    }
}
