//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQNotificationService.Models.Database
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NotificationServiceDbContext : DbContext
    {
        public NotificationServiceDbContext()
            : base("name=NotificationServiceDbContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NSMessageStatu> NSMessageStatus { get; set; }
        public virtual DbSet<NSNotification> NSNotifications { get; set; }
        public virtual DbSet<NSResponse> NSResponses { get; set; }
        public virtual DbSet<NSResponseValue> NSResponseValues { get; set; }
        public virtual DbSet<NSSentSmsMessage> NSSentSmsMessages { get; set; }
    }
}
