//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SQNotificationService.Models.Database
{
    using System;
    using System.Collections.Generic;
    
    public partial class NSNotification
    {
        public NSNotification()
        {
            this.NSMessageStatus = new HashSet<NSMessageStatu>();
            this.NSResponseValues = new HashSet<NSResponseValue>();
            this.NSSentSmsMessages = new HashSet<NSSentSmsMessage>();
        }
    
        public string ExternalReferenceID { get; set; }
        public int MessageID { get; set; }
        public string MessageTitle { get; set; }
        public string Receiver { get; set; }
        public string MessageBody { get; set; }
        public string DeliveryType { get; set; }
        public bool ResponseNeeded { get; set; }
        public string ErrorMessage { get; set; }
        public Nullable<System.DateTime> EndsAt { get; set; }
        public System.DateTime CreatedAt { get; set; }
    
        public virtual ICollection<NSMessageStatu> NSMessageStatus { get; set; }
        public virtual NSResponse NSResponse { get; set; }
        public virtual ICollection<NSResponseValue> NSResponseValues { get; set; }
        public virtual ICollection<NSSentSmsMessage> NSSentSmsMessages { get; set; }
    }
}
